=== giellalt/dict-fkv-nob/dtd/fkvnob.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( nob | eng | fkv ) #IMPLIED
>
<!ATTLIST r
      id ( fkvnob ) #IMPLIED >

<!--
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( nob | sme | sma | swe | eng | deu | smn | fin | fkv| sms | myv | mhr | sjd | rus | smj ) #IMPLIED
 id ( fkvnob | nobfkv ) #IMPLIED
 >
-->

<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT e ( lg, mg+ ) >
<!-- ATTLIST e reverse NMTOKEN #IMPLIED -->
<!ATTLIST e src CDATA #REQUIRED >
<!ATTLIST e dial (p|r|v|pv|rv|pr|prv) #IMPLIED
 id  CDATA #IMPLIED
 reverse (yes) #IMPLIED
 >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos ( A | Abbr | Adv | CC | CS | Clt | Interj |
                  N | Num | Pcle | Phrase | Po | Pr | Pron | Qu | V ) #IMPLIED >
<!ATTLIST l src NMTOKEN #IMPLIED >
<!ATTLIST l stem ( 2syll | 3syll | weak ) #IMPLIED >
<!ATTLIST l t_type ( Phrase ) #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >
<!ATTLIST l val ( IV | TV ) #IMPLIED >
<!ATTLIST l dial (p|j|v|pv|jv|pj) #IMPLIED >
<!ATTLIST l sem_type ( Obj | Org | Plc ) #IMPLIED >
<!ATTLIST l outer_cases ( True | False ) #IMPLIED >
<!ATTLIST l hid CDATA #IMPLIED >
<!ATTLIST l re CDATA #IMPLIED >
<!ATTLIST l context CDATA #IMPLIED >


<!ELEMENT lg ( l, lemma_ref*, stem*, analysis*, mini_paradigm*, algu?) >
<!ELEMENT lemma_ref (#PCDATA) >
<!ATTLIST lemma_ref lemmaID CDATA #IMPLIED >
<!ELEMENT analysis (#PCDATA|wordform)* >
<!ATTLIST analysis ms CDATA #IMPLIED >
<!ELEMENT wordform (#PCDATA) >
<!ELEMENT mini_paradigm (analysis+) >

<!-- algu = lemma IDs in the algu database -->
<!ELEMENT algu EMPTY >
<!ATTLIST algu
      lekseemi_id CDATA #REQUIRED >
<!ATTLIST algu
      sanue_id CDATA #REQUIRED >

<!ELEMENT mg ( re?, tg+ ) >


<!ELEMENT stem ( #PCDATA ) >

<!ELEMENT re ( #PCDATA ) >

<!ELEMENT tg ( re?, t+,  xg*, syng* ) >
<!ATTLIST tg comment CDATA #IMPLIED >
<!ATTLIST tg re CDATA #IMPLIED >
<!ATTLIST tg xml:lang NMTOKEN #FIXED "nob" >
<!ATTLIST tg dial (p|j|v|pv|jv|pj) #IMPLIED >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t gen ( f | m | n ) #IMPLIED >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t pos ( A | Adv | CC | CS | Cp | Det | Interj |
                  N | Num | Phrase | Po | Pr | Pron | V ) #IMPLIED >
<!ATTLIST t t_type ( expl | Phrase )  #IMPLIED >
<!ATTLIST t type ( Prop ) #IMPLIED >

<!ELEMENT xg ( x, xt ) >
<!ATTLIST xg re CDATA #IMPLIED >
<!ELEMENT x ( #PCDATA ) >
<!ELEMENT xt ( #PCDATA ) >

<!ELEMENT syng ( syn+ ) >
<!ELEMENT syn ( #PCDATA ) >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-fkv-nob/src/Pcle_fkvnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/fkvnob.dtd">
<r id="fkvnob" xml:lang="fkv">
   <lics>
      <lic xml:lang="en">This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="ai">
      <lg>
         <l pos="Pcle">altso</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">altså</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pcle">erikoisen</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">spesielt</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pcle">kait</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">vel</t>
            <xg>
               <x>Kait se tullee.</x>
               <xt>Hun kommer vel.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pcle">kauheen</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">forferdelig</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pcle">kunnon</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">skikkelig</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pcle">lähes</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">nesten</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pcle">paitti</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">unntatt</t>
            <xg>
               <x>Kaikki paitti Maija osathaan kainuu.</x>
               <xt>Alle untatt Maija kan kvensk.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">utenom</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="Pcle">pikkusen</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">litt</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pcle">sati</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">bare</t>
         </tg>
      </mg>
   </e>
   <e src="ai;ki">
      <lg>
         <l pos="Pcle">yhä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">fremdeles</t>
            <t pos="Adv">fortsatt</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-fkv-nob/src/CC_fkvnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/fkvnob.dtd">
<r id="fkvnob" xml:lang="fkv">
   <lics>
      <lic xml:lang="en">This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="mj">
      <lg>
         <l pos="CC">ko</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">da</t>
            <t pos="CC">når</t>
            <t pos="CC">enn</t>
            <t pos="CC">som</t>
         </tg>
      </mg>
   </e>
   <e src="mj">
      <lg>
         <l pos="CC">jos</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">hvis</t>
            <t pos="CC">om</t>
         </tg>
      </mg>
   </e>
   <e src="mj">
      <lg>
         <l pos="CC">että</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">at</t>
         </tg>
      </mg>
   </e>
   <e src="ki">
      <lg>
         <l pos="CC">joko</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">enten</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CC">eli</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
            <syng>
               <syn>elikkä</syn>
               <syn>tahi</syn>
            </syng>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CC">ja</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">samt</t>
            <t pos="CC">og</t>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="CC">joko ... tahi</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">enten ... eller</t>
            <xg>
               <x>Met ostama joko kissan tahi koiran.</x>
               <xt>Vi kjøper enten katt eller hund.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="es">
      <lg>
         <l pos="CC">sekä - ette</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">både - og</t>
            <xg>
               <x>Mie puhun sekä norjaa ette kväänii.</x>
               <xt>Jeg snakker både norsk og kvensk.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ki; es">
      <lg>
         <l pos="CC">sekä - ja</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">både - og</t>
            <xg>
               <x>Het tykkäävät sekä korista ja kissoista.</x>
               <xt>De liker både hunder og katter.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CC">mutta</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">men</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CC">sama</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">like</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CC">tahi</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
            <syng>
               <syn>tai</syn>
               <syn>vai</syn>
            </syng>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="CC">tai</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
            <syng>
               <syn>tahi</syn>
               <syn>vai</syn>
            </syng>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="CC">vai</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">eller</t>
            <syng>
               <syn>tahi</syn>
               <syn>tai</syn>
            </syng>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CC">vaikka</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CC">selv om</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CC">vain</l>
      </lg>
      <mg>
         <tg re="i spørsmål" xml:lang="nob">
            <t pos="CC">eller</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-fkv-nob/src/CS_fkvnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/fkvnob.dtd">
<r id="fkvnob" xml:lang="fkv">
   <lics>
      <lic xml:lang="en">This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="ta;ai">
      <lg>
         <l pos="CS">ette</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">at</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CS">ettei</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">at ikke</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CS">jos</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">dersom</t>
            <t pos="CS">hvis</t>
            <t pos="CS">om</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CS">ko</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">da</t>
            <t pos="CS">når</t>
            <t pos="CS">enn</t>
            <t pos="CS">som</t>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="CS">koska</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">fordi</t>
            <t pos="CS">når</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CS">sillä ko</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">fordi</t>
         </tg>
      </mg>
   </e>
   <e src="ki">
      <lg>
         <l pos="CS">siksi ko</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">fordi</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CS">että</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">at</t>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="CS">entä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">enn</t>
            <xg>
               <x>Entä sie?</x>
               <xt>Enn du?</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ki">
      <lg>
         <l pos="CS">napa</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">enn</t>
            <xg>
               <x>Napa sie?</x>
               <xt>Enn du?</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ki">
      <lg>
         <l pos="CS">siksi</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">fordi</t>
            <t pos="CS">for di</t>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">til</t>
            <xg>
               <x>Hän asui sielä siksi ko kuoli.</x>
               <xt>Hun bodde der til hun døde.</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-fkv-nob/src/Abbr_fkvnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/fkvnob.dtd">
<r id="fkvnob" xml:lang="fkv">
   <lics>
      <lic xml:lang="en">This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="ai">
      <lg>
         <l pos="Abbr">nk.</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">såkalt</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-fkv-nob/src/Qu_fkvnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/fkvnob.dtd">
<r id="fkvnob" xml:lang="fkv">
   <lics>
      <lic xml:lang="en">This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="ai">
      <lg>
         <l pos="Qu">enniin</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pron">det meste</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Qu">kolmisen</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Det">ca tre</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Qu">pari</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Det">et par</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Qu">parisen</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Det">to-tre</t>
         </tg>
      </mg>
   </e>
   <e src="ai;es">
      <lg>
         <l pos="Qu">puolitoista</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Det">halvannen</t>
            <xg>
               <x>Minun poika oli silloin puolitoista vuotta ko mie lähđin.</x>
               <xt>Min sønn var halvannet år gammel da jeg dro.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Qu">toistakymmentä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Det">noe over ti</t>
            <t pos="Det">mer enn ti</t>
         </tg>
      </mg>
   </e>
   <e src="ai;es">
      <lg>
         <l pos="Qu">tuhansittain</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">tusenvis</t>
            <xg>
               <x>tuhansittain ihmissii</x>
               <xt>tusenvis av mennesker</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Qu">vähhääkhään</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <re>i negative setninger</re>
            <t pos="A">minste</t>
            <xg>
               <x>ei vähhääkhään</x>
               <xt>ikke det minste</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>
